project:
  type: website
    
website:
  site-url: https://klarahei.github.io/
  repo-url: https://github.com/klarahei/klarahei.github.io/
  favicon: Schaf.jpg
  title: "Klaralicious"
  navbar:
    left:
      - text: "My research"
        href: index.qmd
      - text: "About me"
        href: about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
  
